import type { Metadata } from "next";
import "../styles/index.css";
import ReduxProvider from "@/provider/ReduxProvider";
import Header from "@/components/Header/Header";
import SideBar from "@/components/SideBar/SideBar";

export const metadata: Metadata = {
  title: "Assignment || Side",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <ReduxProvider>
          <Header />
          <main className="flex">
            <div className="lg:flex-[1]">
              <SideBar />
            </div>
            <div className="lg:flex-[5] h-[90vh] overflow-auto w-full px-10 py-8">
              {children}
            </div>
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
